// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInt16Source is a mock of Int16Source interface.
type MockInt16Source struct {
	ctrl     *gomock.Controller
	recorder *MockInt16SourceMockRecorder
}

// MockInt16SourceMockRecorder is the mock recorder for MockInt16Source.
type MockInt16SourceMockRecorder struct {
	mock *MockInt16Source
}

// NewMockInt16Source creates a new mock instance.
func NewMockInt16Source(ctrl *gomock.Controller) *MockInt16Source {
	mock := &MockInt16Source{ctrl: ctrl}
	mock.recorder = &MockInt16SourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt16Source) EXPECT() *MockInt16SourceMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockInt16Source) Read() ([]int16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].([]int16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockInt16SourceMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockInt16Source)(nil).Read))
}
