// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeepgramClient is a mock of DeepgramClient interface.
type MockDeepgramClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeepgramClientMockRecorder
}

// MockDeepgramClientMockRecorder is the mock recorder for MockDeepgramClient.
type MockDeepgramClientMockRecorder struct {
	mock *MockDeepgramClient
}

// NewMockDeepgramClient creates a new mock instance.
func NewMockDeepgramClient(ctrl *gomock.Controller) *MockDeepgramClient {
	mock := &MockDeepgramClient{ctrl: ctrl}
	mock.recorder = &MockDeepgramClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeepgramClient) EXPECT() *MockDeepgramClientMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockDeepgramClient) Connect() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDeepgramClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDeepgramClient)(nil).Connect))
}

// Stream mocks base method.
func (m *MockDeepgramClient) Stream(reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockDeepgramClientMockRecorder) Stream(reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockDeepgramClient)(nil).Stream), reader)
}

// Write mocks base method.
func (m *MockDeepgramClient) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockDeepgramClientMockRecorder) Write(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockDeepgramClient)(nil).Write), p)
}
