// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	pkg "github.com/dTelecom/sdk-ai-bot/pkg"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSpeechToText is a mock of SpeechToText interface.
type MockSpeechToText struct {
	ctrl     *gomock.Controller
	recorder *MockSpeechToTextMockRecorder
}

// MockSpeechToTextMockRecorder is the mock recorder for MockSpeechToText.
type MockSpeechToTextMockRecorder struct {
	mock *MockSpeechToText
}

// NewMockSpeechToText creates a new mock instance.
func NewMockSpeechToText(ctrl *gomock.Controller) *MockSpeechToText {
	mock := &MockSpeechToText{ctrl: ctrl}
	mock.recorder = &MockSpeechToTextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpeechToText) EXPECT() *MockSpeechToTextMockRecorder {
	return m.recorder
}

// Transcribe mocks base method.
func (m *MockSpeechToText) Transcribe(ctx context.Context, r <-chan pkg.AudioChunk) (<-chan pkg.SpeechChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, r)
	ret0, _ := ret[0].(<-chan pkg.SpeechChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockSpeechToTextMockRecorder) Transcribe(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockSpeechToText)(nil).Transcribe), ctx, r)
}

// MockTextProcessor is a mock of TextProcessor interface.
type MockTextProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTextProcessorMockRecorder
}

// MockTextProcessorMockRecorder is the mock recorder for MockTextProcessor.
type MockTextProcessorMockRecorder struct {
	mock *MockTextProcessor
}

// NewMockTextProcessor creates a new mock instance.
func NewMockTextProcessor(ctrl *gomock.Controller) *MockTextProcessor {
	mock := &MockTextProcessor{ctrl: ctrl}
	mock.recorder = &MockTextProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextProcessor) EXPECT() *MockTextProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockTextProcessor) Process(ctx context.Context, question <-chan pkg.TextChunk) (<-chan pkg.TextChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, question)
	ret0, _ := ret[0].(<-chan pkg.TextChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockTextProcessorMockRecorder) Process(ctx, question interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockTextProcessor)(nil).Process), ctx, question)
}

// MockTextToSpeech is a mock of TextToSpeech interface.
type MockTextToSpeech struct {
	ctrl     *gomock.Controller
	recorder *MockTextToSpeechMockRecorder
}

// MockTextToSpeechMockRecorder is the mock recorder for MockTextToSpeech.
type MockTextToSpeechMockRecorder struct {
	mock *MockTextToSpeech
}

// NewMockTextToSpeech creates a new mock instance.
func NewMockTextToSpeech(ctrl *gomock.Controller) *MockTextToSpeech {
	mock := &MockTextToSpeech{ctrl: ctrl}
	mock.recorder = &MockTextToSpeechMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextToSpeech) EXPECT() *MockTextToSpeechMockRecorder {
	return m.recorder
}

// Synthesize mocks base method.
func (m *MockTextToSpeech) Synthesize(ctx context.Context, text <-chan pkg.TextChunk) (<-chan pkg.AudioChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synthesize", ctx, text)
	ret0, _ := ret[0].(<-chan pkg.AudioChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Synthesize indicates an expected call of Synthesize.
func (mr *MockTextToSpeechMockRecorder) Synthesize(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synthesize", reflect.TypeOf((*MockTextToSpeech)(nil).Synthesize), ctx, text)
}
